Description: >
  UdaPeople backend stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "UdaPeople-${ID}"
      GroupDescription: Allow port 22 and port 3030.
      VpcId:
        Fn::ImportValue: UdacityCapstone-VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3030
          ToPort: 3030
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      KeyName: udacity
      ImageId: ami-06b263d6ceff0b3dd
      SubnetId:
        Fn::ImportValue: UdacityCapstone-PUB1-SN
      Tags:
        - Key: Name
          Value: !Sub "backend-${ID}"
