version: 2.1

### It's a good practice to keep your commands at the top of the config file. In this project, you'll need at least 2 commands:

# commands:
#   destroy-environment:
#     description: Destroy backend and frontend cloudformation stacks given a workflow ID.
#     ...

#   revert-migration:
#     description: Revert the last migration if successfully run in the current workflow.
#     ...
orbs:
  slack: circleci/slack@3.4.2

jobs:
  build-frontend:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run:
          name: Build frontend
          command: |
            cd frontend
            npm i
            npm run build
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: "${SLACK_WEBHOOK}"

  build-backend:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run:
          name: Build backend
          command: |
            cd backend
            npm i
            npm run build
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: "${SLACK_WEBHOOK}"

  test-frontend:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run:
          name: Test frontend
          command: |
            cd frontend
            npm i
            npm test
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: "${SLACK_WEBHOOK}"

  test-backend:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run:
          name: Test backend
          command: |
            cd backend
            npm i
            npm test
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: "${SLACK_WEBHOOK}"

  scan-frontend:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run:
          name: Scan vulnerabilities frontend
          command: |
            cd frontend
            npm i
            npm audit fix
            npm audit --audit-level=critical --force
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: "${SLACK_WEBHOOK}"

  scan-backend:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run:
          name: Scan vulnerabilities backend
          command: |
            cd backend
            npm i
            npm audit fix
            npm audit --audit-level=critical --force
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: "${SLACK_WEBHOOK}"

#  deploy-infrastructure:

#  configure-infrastructure:

#  run-migrations:

#  deploy-frontend:

#  deploy-backend:

#  smoke-test:

#  cloudfront-update:

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend:
          requires:
            - build-frontend
      - test-frontend:
          requires:
            - build-backend
      - test-backend:
          requires:
            - test-frontend
      - scan-frontend:
          requires:
            - test-backend
      - scan-backend:
          requires:
            - scan-frontend
