version: 2.1

### It's a good practice to keep your commands at the top of the config file. In this project, you'll need at least 2 commands:

commands:
  deploy-stack:
    parameters:
      stack_name:
        default: "null"
        type: string
    steps:
      - run:
          name: Deploy infrastructure
          command: |
            aws cloudformation deploy \
              --template-file ".circleci/files/<<parameters.stack_name>>.yml" \
              --stack-name "udapeople-<<parameters.stack_name>>-${CIRCLE_WORKFLOW_ID}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}" \
              --tags project=udapeople
            aws cloudformation wait stack-create-complete --stack-name "udapeople-<<parameters.stack_name>>-${CIRCLE_WORKFLOW_ID}"

  destroy-environment:
    description: Destroy backend and frontend cloudformation stacks given a workflow ID.
    steps:
      - run:
          name: Clear backend infrastructure
          command: |
            aws cloudformation delete-stack --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID}"
          when: on_fail
      - run:
          name: Clear frontend infrastructure
          command: |
            aws s3 rm "s3://udapeople-${CIRCLE_WORKFLOW_ID}" --recursive
            aws cloudformation delete-stack --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID}"
          when: on_fail

  clean-environment:
    description: Clean backend and frontend cloudformation stacks given a workflow ID.
    steps:
      - run:
          name: Clear backend infrastructure
          command: |
            STACK_ID=$(curl -H 'token: 095cef7a-185c-43c6-aa1c-a479edebe4e7' --request GET https://api.memstash.io/values/previousworkflow)
            aws cloudformation delete-stack --stack-name "udapeople-backend-${STACK_ID}"
      - run:
          name: Clear frontend infrastructure
          command: |
            aws s3 rm "s3://udapeople-${STACK_ID}" --recursive
            aws cloudformation delete-stack --stack-name "udapeople-frontend-${STACK_ID}"

  install-ansible:
    description: Command that install ansible in an ubuntu machine
    steps:
      - run:
          name: Install Ansible
          command: |
            #sudo apt update
            #sudo apt install software-properties-common -y
            #sudo apt-add-repository --yes --update ppa:ansible/ansible
            #sudo apt install ansible -y
            #sudo python get-pip.py
            sudo pip install ansible

  revert-migration:
    description: Revert the last migration if successfully run in the current workflow.
    steps:
      - run:
          name: Revert migrations
          command: |
            cd backend
            npm run migrations:revert
          when: on_fail

orbs:
  slack: circleci/slack@3.4.2

jobs:
  build-frontend:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run:
          name: Build frontend
          command: |
            cd frontend
            npm i
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - frontend
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: "${SLACK_WEBHOOK}"

  build-backend:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run:
          name: Build backend
          command: |
            cd backend
            npm i
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - backend
            - .circleci
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: "${SLACK_WEBHOOK}"

  test-frontend:
    docker:
      - image: cimg/node:12.16
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test frontend
          command: |
            cd frontend
            npm test
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: "${SLACK_WEBHOOK}"

  test-backend:
    docker:
      - image: cimg/node:12.16
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test backend
          command: |
            cd backend
            npm i
            npm test
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: "${SLACK_WEBHOOK}"

  scan-frontend:
    docker:
      - image: cimg/node:12.16
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Scan vulnerabilities frontend
          command: |
            cd frontend
            npm audit fix
            npm audit --audit-level=critical --force
      - persist_to_workspace:
          root: .
          paths:
            - frontend
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: "${SLACK_WEBHOOK}"

  scan-backend:
    docker:
      - image: cimg/node:12.16
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Scan vulnerabilities backend
          command: |
            cd backend
            npm audit fix
            npm audit --audit-level=critical --force
      - persist_to_workspace:
          root: .
          paths:
            - backend
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: "${SLACK_WEBHOOK}"

  deploy-infrastructure-frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - deploy-stack:
          stack_name: frontend
      - destroy-environment
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: "${SLACK_WEBHOOK}"

  deploy-infrastructure-backend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - deploy-stack:
          stack_name: backend
      - run:
          name: Register backend infrastructure
          command: |
            FILTER="Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID}"
            BACKEND_URL=$(aws ec2 describe-instances \
              --filters $FILTER \
              --query "Reservations[*].Instances[*].PublicIpAddress" \
              --output=text)
            curl -H "Content-Type: text/plain" -H "token: 095cef7a-185c-43c6-aa1c-a479edebe4e7" \
              --request PUT \
              --data "${BACKEND_URL}" \
              "https://api.memstash.io/values/backendurl"
      # curl -H "token: 095cef7a-185c-43c6-aa1c-a479edebe4e7" --request GET https://api.memstash.io/values/backendurl
      - destroy-environment
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: "${SLACK_WEBHOOK}"

  configure-infrastructure:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "91:d6:ae:8b:2b:8a:8a:1a:8c:b6:01:fd:81:70:a8:7d"
      - install-ansible
      - run:
          name: Run ansible playbook
          command: |
            BACKEND_URL=$(curl -H "token: 095cef7a-185c-43c6-aa1c-a479edebe4e7" \
              --request GET https://api.memstash.io/values/backendurl)
            cd ./.circleci/ansible/configure-server
            echo [web] > inventory.txt
            echo $BACKEND_URL >> inventory.txt
            export ANSIBLE_HOST_KEY_CHECKING=False
            ansible-playbook main.yml --private-key "~/.ssh/id_rsa" -i inventory.txt
      - destroy-environment
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: "${SLACK_WEBHOOK}"

  run-migrations:
    docker:
      - image: cimg/node:12.16
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run migrations
          command: |
            cd backend
            npm run migrations

  deploy-frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: Install missing packages
          command: |
            yum install -y tar
            yum install -y gzip
            curl -sL https://rpm.nodesource.com/setup_10.x | bash -
            yum install -y nodejs
      - attach_workspace:
          at: .
      - run:
          name: Deploy code to s3
          command: |
            API_URL=$(curl -H "token: 095cef7a-185c-43c6-aa1c-a479edebe4e7" \
              --request GET https://api.memstash.io/values/backendurl)
            cd ./frontend
            npm run build
            aws s3 sync ./dist "s3://udapeople-${CIRCLE_WORKFLOW_ID}"

      - destroy-environment
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: "${SLACK_WEBHOOK}"

  deploy-backend:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "91:d6:ae:8b:2b:8a:8a:1a:8c:b6:01:fd:81:70:a8:7d"
      - install-ansible
      - run:
          name: Run ansible playbook
          command: |
            BACKEND_URL=$(curl -H "token: 095cef7a-185c-43c6-aa1c-a479edebe4e7" \
              --request GET https://api.memstash.io/values/backendurl)
            ls ./backend/dist
            cp -R ./backend/dist ./.circleci/ansible/deploy/roles/deploy-code/files/dist
            cp ./backend/package.json ./.circleci/ansible/deploy/roles/deploy-code/files/package.json
            cd ./.circleci/ansible/deploy
            echo [web] > inventory.txt
            echo $BACKEND_URL >> inventory.txt
            export ANSIBLE_HOST_KEY_CHECKING=False
            ansible-playbook main.yml --private-key "~/.ssh/id_rsa" -i inventory.txt
      - destroy-environment
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: "${SLACK_WEBHOOK}"

  smoke-test:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: Install missing packages
          command: |
            yum install -y tar
            yum install -y gzip
            curl -sL https://rpm.nodesource.com/setup_10.x | bash -
            yum install -y nodejs
      - attach_workspace:
          at: .
      - run:
          name: Smoke test backend
          command: |
            FILTER="Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID}"
            BACKEND_IP=$(aws ec2 describe-instances \
              --filters $FILTER \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --output text)
            curl "http://${BACKEND_IP}:3030/api/status"

      - run:
          name: Smoke test frontend
          command: |
            URL="http://udapeople-${CIRCLE_WORKFLOW_ID}.s3-website-us-east-1.amazonaws.com/#/employees"            
            if curl -s ${URL} | grep "Welcome"
            then
            exit 0
            else
            exit 1
            fi

      - destroy-environment
      - revert-migration
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: "${SLACK_WEBHOOK}"

  cloudfront-update:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: Install missing packages
          command: |
            yum install -y tar
            yum install -y gzip
            curl -sL https://rpm.nodesource.com/setup_10.x | bash -
            yum install -y nodejs
      - attach_workspace:
          at: .
      - run:
          name: Update cloudfront with new bucket
          command: |
            aws cloudformation update-stack \
              --template-body "file://.circleci/files/cloudfront.yml" \
              --stack-name "udapeople-cdn" \
              --parameters "ParameterKey=WorkflowID,ParameterValue=${CIRCLE_WORKFLOW_ID}" \

      - clean-environment
      - run:
          name: Register old environment
          command: |
            curl -H "Content-Type: text/plain" -H "token: 095cef7a-185c-43c6-aa1c-a479edebe4e7" \
              --request PUT \
              --data "${CIRCLE_WORKFLOW_ID}" \
              "https://api.memstash.io/values/previousworkflow"
      - destroy-environment
      - revert-migration
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: "${SLACK_WEBHOOK}"

workflows:
  version: 2
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires:
            - build-frontend
      - test-backend:
          requires:
            - build-backend
      - scan-frontend:
          requires:
            - build-frontend
      - scan-backend:
          requires:
            - build-backend
      - deploy-infrastructure-frontend:
          requires:
            - test-frontend
            - test-backend
            - scan-backend
            - scan-frontend
          filters:
            branches:
              only:
                - master
      - deploy-infrastructure-backend:
          requires:
            - test-frontend
            - test-backend
            - scan-backend
            - scan-frontend
          filters:
            branches:
              only:
                - master
      - configure-infrastructure:
          requires:
            - deploy-infrastructure-backend
      - run-migrations:
          requires:
            - configure-infrastructure
      - deploy-frontend:
          requires:
            - deploy-infrastructure-frontend
            - deploy-infrastructure-backend
      - deploy-backend:
          requires:
            - run-migrations
      - smoke-test:
          requires:
            - deploy-backend
            - deploy-frontend
      - cloudfront-update:
          requires:
            - smoke-test
