---
- name: copy build
  become: true
  copy:
    src: dist
    dest: /home/ubuntu
    backup: yes

- name: run pm2
  shell: |
    ENVIRONMENT=production \
    TYPEORM_CONNECTION=postgres \
    TYPEORM_ENTITIES="./dist/modules/domain/**/*.entity{.ts,.js}" \
    TYPEORM_HOST=udapeople1.c0dflfjnllnb.us-east-1.rds.amazonaws.com \
    TYPEORM_PORT=5432 \
    TYPEORM_USERNAME=udapeople \
    TYPEORM_PASSWORD=udapeople \
    TYPEORM_DATABASE=udapeople \
    pm2 start ./dist/main.js
